export const projects = [
  { id: '01', title: 'A smarter service desk.', name: 'Multi-tenant Ticketing Platform', category: 'Fullstack development', year: '2025 — 2026', tags: ['Goravel', 'Hypervel', 'Nuxt.js', 'PostgreSQL', 'WebSocket', 'Redis'], type: 'ticket', description: 'Building the infrastructure for better customer support.', details: 'Developed at PT. Solusi Tiga Selaras (Solutif) during the MagangHub Batch 3 internship. Built the backend with Goravel and Hypervel and the frontend with Nuxt.js, backed by PostgreSQL and Redis. Designed schema-based tenant isolation and cross-tenant materialized views. Built an automated SLA matching engine, real-time ticket escalation, email thread tracking, WebSocket user presence, and CSAT reporting with sentiment analysis. Refactored state management with Vue Query and documented APIs with OpenAPI, AsyncAPI, and Mockoon.' },
  { id: '02', title: 'Small bin. Big possibilities.', name: 'Smart Bin · Inorganic Waste Classification', category: 'Machine learning', year: '2025', tags: ['Python', 'MobileNetV2', 'Transfer Learning'], type: 'bin', description: 'Teaching a machine to make a little less waste.', details: 'Undergraduate thesis project at Diponegoro University. Developed the machine learning component of a Smart Bin using MobileNetV2 transfer learning to classify four categories of inorganic waste: bottles, cans, paper, and others. The project connects computer engineering with a practical waste-sorting application.' },
  { id: '03', title: 'Every attendance counts.', name: 'SIMTEG · Student Event Attendance', category: 'Fullstack development', year: '2024', tags: ['PHP', 'CodeIgniter 3', 'MySQL'], type: 'attendance', description: 'Helping an education team keep everyone connected.', details: 'Contributed as a Fullstack Developer Intern at PT. Bintang Pelajar from January to February 2024. Assisted the team in developing a new menu in SIMTEG, the integrated system used by Bintang Pelajar, for student event attendance.' },
];
export const skills = [
  { title: 'Languages & web', items: ['HTML5', 'CSS3', 'JavaScript', 'TypeScript', 'PHP', 'Go', 'React.js', 'Vue.js'] },
  { title: 'Frameworks & runtimes', items: ['Next.js', 'Nuxt.js', 'Laravel', 'CodeIgniter 3', 'Node.js'] },
  { title: 'Data & communication', items: ['MySQL', 'PostgreSQL', 'Redis', 'REST API', 'WebSocket', 'Swagger / AsyncAPI'] },
  { title: 'Tools & deployment', items: ['Docker', 'Kubernetes', 'CI/CD', 'Git', 'Postman', 'Mockoon', 'ESLint', 'VS Code', 'Cursor', 'Opencode'] },
];
export const certifications = [
  ['B1 English for Developers', 'freeCodeCamp', '2026'], ['Backend Development and APIs', 'freeCodeCamp', '2026'], ['MagangHub Fullstack Developer Intern', 'MagangHub · Solutif', '2026'], ['TOEFL ITP', 'Brighten English · BE427100/I/2025', '2025'], ['Frontend Development Libraries', 'freeCodeCamp', '2025'], ['Machine Learning with Python', 'freeCodeCamp', '2025'], ['Computing with Python', 'freeCodeCamp', '2025'], ['Scientific JavaScript Algorithms and Data Structures', 'freeCodeCamp', '2025'], ['Data Visualization', 'freeCodeCamp', '2025'], ['Responsive Web Design', 'freeCodeCamp', '2023'], ['Oracle Database Design', 'Oracle', '2023'], ['Oracle Database Foundation', 'Oracle', '2023'],
];
