'use client';

import dynamic from 'next/dynamic';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useReducedMotion } from 'motion/react';
import { ArrowDown, ArrowLeft, ArrowUpRight, Check, Copy, Expand, Menu, MoveUpRight, Pause, Play, RotateCcw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { chapters, type JourneyDetail, type JourneyMotion } from '@/lib/journey';
import { projects, skills, certifications } from '@/lib/portfolio';

const World=dynamic(()=>import('@/components/macbook'),{ssr:false});

export default function Home(){
  const [chapter,setChapter]=useState(0);const [free,setFree]=useState(false);const [paused,setPaused]=useState(false);const [menu,setMenu]=useState(false);const [detail,setDetail]=useState<JourneyDetail>(null);const [loaded,setLoaded]=useState(false);const [failed,setFailed]=useState(false);const [reset,setReset]=useState(0);const [copied,setCopied]=useState(false);
  const drag=useRef({x:0,y:0,moved:false});
  const reduced=useReducedMotion();const scene=useRef<JourneyMotion>({progress:0,paused:false});const progressBar=useRef<HTMLDivElement>(null);const scrollFrame=useRef(0);
  const ready=useCallback(()=>{setLoaded(true);setFailed(false)},[]);const fail=useCallback(()=>{setFailed(true);setLoaded(true)},[]);
  useEffect(()=>{scene.current.paused=paused||!!reduced||!!detail||menu},[paused,reduced,detail,menu]);
  useEffect(()=>{
    const update=()=>{const range=document.documentElement.scrollHeight-window.innerHeight;const p=Math.max(0,Math.min(4,window.scrollY/Math.max(1,range)*4));scene.current.progress=p;setChapter(Math.round(p));if(progressBar.current)progressBar.current.style.transform=`scaleX(${p/4})`;};
    const scroll=()=>{cancelAnimationFrame(scrollFrame.current);scrollFrame.current=requestAnimationFrame(update)};
    update();window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',scroll);
    return()=>{window.removeEventListener('scroll',scroll);window.removeEventListener('resize',scroll);cancelAnimationFrame(scrollFrame.current)};
  },[]);
  const go=useCallback((index:number)=>{setFree(false);setMenu(false);window.scrollTo({top:(document.documentElement.scrollHeight-window.innerHeight)*index/4,behavior:reduced?'instant':'smooth'})},[reduced]);
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(menu||detail||e.altKey||e.metaKey||e.ctrlKey||(e.target instanceof HTMLElement&&e.target.closest('button,a,input,textarea')))return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();go(Math.min(chapter+1,4))}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(Math.max(chapter-1,0))}if(e.key==='Home'){e.preventDefault();go(0)}if(e.key==='End'){e.preventDefault();go(4)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[chapter,detail,go,menu]);
  async function copy(){try{await navigator.clipboard.writeText('rizqyyourin6@gmail.com');setCopied(true);setTimeout(()=>setCopied(false),2200)}catch{window.location.href='mailto:rizqyyourin6@gmail.com'}}
  const data=chapters[chapter];
  function action(){if(chapter===0)go(1);else setDetail((['projects','skills','journey','contact'] as const)[chapter-1])}
  return <>
    <a className="skip-link" href="#chapter-controls">Skip to chapter navigation</a>
    <div className="scroll-journey" aria-hidden="true"/>
    <main className={`experience ${free?'is-exploring':''}`} data-chapter={data.name}>
      <div className="ambient-wash"/>
      <div className="backdrop-type" aria-hidden="true"><div key={chapter} className="chapter-reveal"><span>{data.title[0]}</span><span>{data.title[1]}</span></div></div>
      <div className="world" onPointerDownCapture={e=>{drag.current={x:e.clientX,y:e.clientY,moved:false}}} onPointerMoveCapture={e=>{if(e.buttons&&Math.hypot(e.clientX-drag.current.x,e.clientY-drag.current.y)>7)drag.current.moved=true}} onClickCapture={e=>{if(drag.current.moved){e.preventDefault();e.stopPropagation()}}} aria-label="Interactive 3D portfolio. Scroll to travel; select objects to explore." style={{touchAction:free?'none':'pan-y'}}><World motion={scene} chapter={chapter} free={free} reduced={!!reduced} onSelect={setDetail} onReady={ready} onError={fail} reset={reset}/></div>
      <div className="vignette" aria-hidden="true"/>
      <header className="hud-header"><button className="wordmark" aria-label="Return to beginning" onClick={()=>go(0)}>yourin<span>®</span></button><span className="header-description">INDEPENDENT MIND.<br/>FULLSTACK DEVELOPER.</span><div className="header-right"><span className="availability"><i/> OPEN TO OPPORTUNITIES</span><button className="index-button" onClick={()=>setMenu(true)} aria-label="Open chapter menu">INDEX <Menu size={17}/></button></div></header>
      <div className="chapter-eyebrow"><span className="crosshair">+</span><span>{data.label}</span><span className="edition">INTERACTIVE EDITION / 2026</span></div>
      <div className="scene-index" aria-hidden="true"><span>0{chapter+1}</span><span>/ 05</span></div>
      <div className="scene-caption"><div key={chapter} className="chapter-reveal"><h1>{data.caption}</h1><p>{data.detail}</p></div><button className="chapter-action" onClick={action}>{data.action}<ArrowUpRight size={16}/></button></div>
      <div className="scene-tools"><button aria-label={free?'Return to scroll journey':'Explore freely'} aria-pressed={free} onClick={()=>setFree(!free)}><Expand size={16}/><span>{free?'SCROLL MODE':'FREE EXPLORE'}</span></button><button aria-label={paused?'Resume ambient motion':'Pause ambient motion'} aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?<Play size={15}/>:<Pause size={15}/>}</button><button aria-label="Reset view" onClick={()=>{setFree(false);setReset(r=>r+1)}}><RotateCcw size={15}/></button></div>
      {free&&<div className="explore-hint">DRAG TO ORBIT · 360°<button onClick={()=>setFree(false)}>Done <Check size={13}/></button></div>}
      {!loaded&&!failed&&<div className="loading-note" role="status"><span className="loading-ring"/> ASSEMBLING YOUR WORKSPACE</div>}
      {failed&&<div className="loading-note load-error" role="alert" aria-label="3D loading error">The 3D workspace couldn’t load.<button onClick={()=>{setFailed(false);setLoaded(false);setReset(n=>n+1)}}>Retry <RotateCcw size={13}/></button><button onClick={()=>setDetail('projects')}>Explore work <ArrowUpRight size={13}/></button></div>}
      <footer className="hud-footer"><div className="scroll-instruction"><span className="scroll-icon"><ArrowDown size={15}/></span><span>{chapter===4?'END OF THE JOURNEY':'SCROLL TO DISCOVER'}{chapter===4&&<small>OR THE START OF SOMETHING</small>}</span></div><nav id="chapter-controls" className="chapter-nav" aria-label="Journey chapters">{chapters.map((c,i)=><button key={c.name} aria-label={`Go to ${c.name}`} aria-current={chapter===i?'step':undefined} onClick={()=>go(i)}><span className="nav-dot"/><span className="nav-name">{c.name}</span></button>)}</nav><div className="footer-meta"><button onClick={()=>setDetail('credits')}>CREDITS <MoveUpRight size={10}/></button></div></footer>
      <div className="journey-progress"><div ref={progressBar}/></div>
    </main>
    <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="index-modal"><DialogTitle className="index-title">Choose your destination.</DialogTitle><DialogDescription className="index-description">Five perspectives. One workspace.</DialogDescription><nav aria-label="Chapter index">{chapters.map((c,i)=><button key={c.name} onClick={()=>go(i)}><span>0{i+1}</span><strong>{c.name}</strong><ArrowUpRight/></button>)}</nav><div className="index-footer"><span>Ahmad Rizqy Yourin</span><div><button onClick={()=>{setMenu(false);setDetail('credits')}}>CREDITS ↗</button><a href="mailto:rizqyyourin6@gmail.com">LET’S TALK ↗</a></div></div></DialogContent></Dialog>
    <Dialog open={detail!==null} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="detail-modal"><DetailContent detail={detail} setDetail={setDetail} copied={copied} copy={copy}/></DialogContent></Dialog>
  </>;
}

function DetailContent({detail,setDetail,copied,copy}:{detail:JourneyDetail;setDetail:(d:JourneyDetail)=>void;copied:boolean;copy:()=>void}){
  if(detail?.startsWith('project-')){const index=Number(detail.split('-')[1]);const p=projects[index];return <><button className="back-link" onClick={()=>setDetail('projects')}><ArrowLeft size={13}/> All projects</button><span className="detail-eyebrow">{p.category} / {p.year}</span><DialogTitle className="detail-title">{p.name}</DialogTitle><DialogDescription className="detail-description">{p.details}</DialogDescription><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><a className="detail-link" href="mailto:rizqyyourin6@gmail.com">Discuss this project <ArrowUpRight size={16}/></a></>}
  if(detail==='projects')return <><span className="detail-eyebrow">01 / SELECTED WORK</span><DialogTitle className="detail-title">Ideas, made real.</DialogTitle><DialogDescription className="detail-description">Select a project to explore the problem and my contribution.</DialogDescription><div className="project-index">{projects.map((p,i)=><button key={p.id} onClick={()=>setDetail(`project-${i}`)}><span>{p.id}</span><div><h3>{p.name}</h3><small>{p.category} / {p.year}</small></div><ArrowUpRight size={19}/></button>)}</div></>;
  if(detail==='skills')return <><span className="detail-eyebrow">02 / UNDER THE HOOD</span><DialogTitle className="detail-title">Across the stack.</DialogTitle><DialogDescription className="detail-description">The tools I use to connect a thoughtful interface with the systems behind it.</DialogDescription>{skills.map(s=><div className="skill-detail" key={s.title}><h3>{s.title}</h3><div className="tags">{s.items.map(t=><span key={t}>{t}</span>)}</div></div>)}<p className="soft-skills-detail">Technologically adaptive · Teamwork & collaboration · Effective communication · Critical thinking & problem solving</p></>;
  if(detail==='journey')return <><span className="detail-eyebrow">03 / ALWAYS BECOMING</span><DialogTitle className="detail-title">Learning by doing.</DialogTitle><DialogDescription className="detail-description">Ahmad Rizqy Yourin — Computer Engineering graduate and fullstack developer based in North Jakarta.</DialogDescription><div className="journey-detail"><article><span>DEC 2025 — JUN 2026</span><h3>PT. Solusi Tiga Selaras · Solutif</h3><h4>Fullstack Developer Intern / MagangHub Batch 3</h4><p>Schema-based multi-tenant isolation, cross-tenant materialized views, an automated SLA engine, and real-time ticket escalation. Ticket handling, email threads, WebSocket presence, CSAT reporting with sentiment analysis, Vue Query optimistic updates, and OpenAPI / AsyncAPI documentation with Mockoon.</p></article><article><span>JAN — FEB 2024</span><h3>PT. Bintang Pelajar</h3><h4>Fullstack Developer Intern</h4><p>Helped develop student event attendance for SIMTEG using CodeIgniter 3.</p></article><article><span>2021 — 2025</span><h3>Diponegoro University</h3><h4>Bachelor of Computer Engineering · GPA 3.64 / 4.00</h4><p>Undergraduate thesis: Smart Bin using MobileNetV2 transfer learning to classify bottles, cans, paper, and other inorganic waste.</p></article></div><details className="certificates"><summary>Certifications <span>{certifications.length} credentials +</span></summary>{certifications.map(([name,issuer,year])=><div key={name}><h4>{name}</h4><span>{issuer} / {year}</span></div>)}</details></>;
  if(detail==='contact')return <><span className="detail-eyebrow">04 / LET’S MAKE SOMETHING</span><DialogTitle className="detail-title">Your idea.<br/>Our next chapter.</DialogTitle><DialogDescription className="detail-description">Open to fullstack roles, interesting projects, and a good conversation.</DialogDescription><a className="contact-email" href="mailto:rizqyyourin6@gmail.com">rizqyyourin6@gmail.com <ArrowUpRight size={20}/></a><Button variant="outline" size="sm" onClick={copy}>{copied?<Check/>:<Copy/>}{copied?'Copied!':'Copy email'}</Button><div role="status" className="sr-only">{copied?'Email copied to clipboard':''}</div><div className="contact-links"><a href="https://www.linkedin.com/in/rizqyyourin" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={15}/></a><a href="tel:+6285774414941">+62 857 7441 4941 <ArrowUpRight size={15}/></a></div><p className="contact-location">Tugu Utara, Koja, North Jakarta · Indonesia</p></>;
  return <><span className="detail-eyebrow">THE PEOPLE & TOOLS BEHIND THE EXPERIENCE</span><DialogTitle className="detail-title">Made with curiosity.</DialogTitle><DialogDescription className="detail-description">Portfolio of Ahmad Rizqy Yourin. Built with Next.js, React Three Fiber, Three.js, Tailwind, shadcn/Radix, Motion, and Lucide.</DialogDescription><p className="credit-text">3D <a href="https://sketchfab.com/3d-models/macbook-289c013e6c0541f498d4c6b40045db88" target="_blank" rel="noreferrer">MacBook</a> by <a href="https://sketchfab.com/imamulhasan" target="_blank" rel="noreferrer">M I H</a>, licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>. Adaptations: scale, screen overlay, lighting, motion, and scene composition.</p><p className="credit-text">Project visuals are illustrative representations. No unprovided project or certificate links are invented.</p></>;
}
